export const locations = {
	Airplane: {
		name: "Airplane",
		version: 1,
		roles: [
			"First Class Passenger",
			"Air Marshal",
			"Mechanic",
			"Air Hostess",
			"Co-Pilot",
			"Captain",
			"Economy Class Passenger",
		],
	},
	Bank: {
		name: "Bank",
		version: 1,
		roles: ["Armored Car Driver", "Manager", "Consultant", "Robber", "Security Guard", "Teller", "Customer"],
	},
	Beach: {
		name: "Beach",
		version: 1,
		roles: [
			"Beach Waitress",
			"Kite Surfer",
			"Lifeguard",
			"Thief",
			"Beach Photographer",
			"Ice Cream Truck Driver",
			"Beach Goer",
		],
	},
	Cathedral: {
		name: "Cathedral",
		version: 1,
		roles: ["Priest", "Beggar", "Sinner", "Tourist", "Sponsor", "Chorister", "Parishioner"],
	},
	"Circus Tent": {
		name: "Circus Tent",
		version: 1,
		roles: ["Acrobat", "Animal Trainer", "Magician", "Fire Eater", "Clown", "Juggler", "Visitor"],
	},
	"Corporate Party": {
		name: "Corporate Party",
		version: 1,
		roles: ["Entertainer", "Manager", "Unwanted Guest", "Owner", "Secretary", "Delivery Boy", "Accountant"],
	},
	"Crusader Army": {
		name: "Crusader Army",
		version: 1,
		roles: ["Monk", "Imprisoned Saracen", "Servant", "Bishop", "Squire", "Archer", "Knight"],
	},
	Casino: {
		name: "Casino",
		version: 1,
		roles: ["Bartender", "Head Security Guard", "Bouncer", "Manager", "Hustler", "Dealer", "Gambler"],
	},
	"Day Spa": {
		name: "Day Spa",
		version: 1,
		roles: ["Stylist", "Masseuse", "Manicurist", "Makeup Artist", "Dermatologist", "Beautician", "Customer"],
	},
	Embassy: {
		name: "Embassy",
		version: 1,
		roles: ["Security Guard", "Secretary", "Ambassador", "Tourist", "Refugee", "Diplomat", "Government Official"],
	},
	Hospital: {
		name: "Hospital",
		version: 1,
		roles: ["Nurse", "Doctor", "Anesthesiologist", "Intern", "Therapist", "Surgeon", "Patient"],
	},
	Hotel: {
		name: "Hotel",
		version: 1,
		roles: ["Doorman", "Security Guard", "Manager", "Housekeeper", "Bartender", "Bellman", "Customer"],
	},
	"Military Base": {
		name: "Military Base",
		version: 1,
		roles: ["Deserter", "Colonel", "Medic", "Sniper", "Officer", "Tank Engineer", "Soldier"],
	},
	"Movie Studio": {
		name: "Movie Studio",
		version: 1,
		roles: ["Stunt Man", "Sound Engineer", "Camera Man", "Director", "Costume Artist", "Producer", "Actor"],
	},
	"Ocean Liner": {
		name: "Ocean Liner",
		version: 1,
		roles: ["Cook", "Captain", "Bartender", "Musician", "Waiter", "Mechanic", "Rich Passenger"],
	},
	"Passenger Train": {
		name: "Passenger Train",
		version: 1,
		roles: [
			"Mechanic",
			"Border Patrol",
			"Train Attendant",
			"Restaurant Chef",
			"Train Driver",
			"Stoker",
			"Passenger",
		],
	},
	"Pirate Ship": {
		name: "Pirate Ship",
		version: 1,
		roles: ["Cook", "Slave", "Cannoneer", "Tied Up Prisoner", "Cabin Boy", "Brave Captain", "Sailor"],
	},
	"Polar Station": {
		name: "Polar Station",
		version: 1,
		roles: ["Medic", "Expedition Leader", "Biologist", "Radioman", "Hydrologist", "Meteorologist", "Geologist"],
	},
	"Police Station": {
		name: "Police Station",
		version: 1,
		roles: ["Detective", "Lawyer", "Journalist", "Criminalist", "Archivist", "Criminal", "Patrol Officer"],
	},
	Restaurant: {
		name: "Restaurant",
		version: 1,
		roles: ["Musician", "Bouncer", "Hostess", "Head Chef", "Food Critic", "Waiter", "Customer"],
	},
	School: {
		name: "School",
		version: 1,
		roles: [
			"Gym Teacher",
			"Principal",
			"Security Guard",
			"Janitor",
			"Cafeteria Lady",
			"Maintenance Man",
			"Student",
		],
	},
	"Service Station": {
		name: "Service Station",
		version: 1,
		roles: [
			"Manager",
			"Tire Specialist",
			"Biker",
			"Car Owner",
			"Car Wash Operator",
			"Electrician",
			"Auto Mechanic",
		],
	},
	"Space Station": {
		name: "Space Station",
		version: 1,
		roles: ["Engineer", "Alien", "Pilot", "Commander", "Scientist", "Doctor", "Space Tourist"],
	},
	Submarine: {
		name: "Submarine",
		version: 1,
		roles: ["Cook", "Commander", "Sonar Technician", "Electronics Technician", "Radioman", "Navigator", "Sailor"],
	},
	Supermarket: {
		name: "Supermarket",
		version: 1,
		roles: [
			"Cashier",
			"Butcher",
			"Janitor",
			"Security Guard",
			"Food Sample Demonstrator",
			"Shelf Stocker",
			"Customer",
		],
	},
	Theater: {
		name: "Theater",
		version: 1,
		roles: ["Coat Check Lady", "Prompter", "Cashier", "Director", "Actor", "Crew Man", "Audience Member"],
	},
	University: {
		name: "University",
		version: 1,
		roles: ["Graduate Student", "Professor", "Dean", "Psychologist", "Maintenance Man", "Janitor", "Student"],
	},
	"World War II Squad": {
		name: "World War II Squad",
		version: 2,
		roles: ["Resistance Fighter", "Radioman", "Scout", "Medic", "Cook", "Imprisoned Nazi", "Soldier"],
	},
	"Race Track": {
		name: "Race Track",
		version: 2,
		roles: [
			"Team Owner",
			"Driver",
			"Engineer",
			"Spectator",
			"Referee",
			"Mechanic",
			"Food Vendor",
			"Commentator",
			"Bookmaker",
		],
	},
	"Art Museum": {
		name: "Art Museum",
		version: 2,
		roles: [
			"Ticket Seller",
			"Student",
			"Visitor",
			"Teacher",
			"Security Guard",
			"Painter",
			"Art Collector",
			"Art Critic",
			"Photographer",
			"Tourist",
		],
	},
	Vineyard: {
		name: "Vineyard",
		version: 2,
		roles: [
			"Gardener",
			"Gourmet Guide",
			"Winemaker",
			"Exporter",
			"Butler",
			"Wine Taster",
			"Sommelier",
			"Owner",
			"Vineyard Manager",
			"Oenologist",
		],
	},
	"Baseball Stadium": {
		name: "Baseball Stadium",
		version: 2,
		roles: [
			"Pitcher",
			"Catcher",
			"Commentator",
			"Spectator",
			"Security Guard",
			"Umpire",
			"Food Vendor",
			"Manager",
			"First Baseman",
			"Shortstop",
			"Outfielder",
			"Second Baseman",
			"Third Baseman",
			"Mascot",
			"Team Owner",
		],
	},
	Library: {
		name: "Library",
		version: 2,
		roles: [
			"Old Man",
			"Journalist",
			"Author",
			"Volunteer",
			"Know-It-All",
			"Student",
			"Librarian",
			"Loudmouth",
			"Book Fanatic",
			"Nerd",
		],
	},
	"Cat Show": {
		name: "Cat Show",
		version: 2,
		roles: [
			"Judge",
			"Cat-Handler",
			"Veterinarian",
			"Security Guard",
			"Cat Trainer",
			"Crazy Cat Lady",
			"Animal Lover",
			"Cat Owner",
			"Cat",
		],
	},
	"Retirement Home": {
		name: "Retirement Home",
		version: 2,
		roles: [
			"Relative",
			"Cribbage Player",
			"Old Person",
			"Nurse",
			"Janitor",
			"Cook",
			"Blind Person",
			"Psychologist",
		],
	},
	Jail: {
		name: "Jail",
		version: 2,
		roles: [
			"Wrongly Accused Man",
			"CCTV Operator",
			"Guard",
			"Visitor",
			"Lawyer",
			"Janitor",
			"Jailkeeper",
			"Criminal",
			"Correctional Officer",
			"Maniac",
		],
	},
	"Construction Site": {
		name: "Construction Site",
		version: 2,
		roles: [
			"Free-Roaming Toddler",
			"Contractor",
			"Crane Driver",
			"Trespasser",
			"Safety Officer",
			"Electrician",
			"Engineer",
			"Architect",
			"Construction Worker",
		],
	},
	"The United Nations": {
		name: "The United Nations",
		version: 2,
		roles: [
			"Diplomat",
			"Interpreter",
			"Blowhard",
			"Tourist",
			"Napping Delegate",
			"Journalist",
			"Secretary of State",
			"Speaker",
			"Secretary General",
			"Lobbyist",
		],
	},
	"Candy Factory": {
		name: "Candy Factory",
		version: 2,
		roles: [
			"Candy Maker",
			"Pastry Chef",
			"Visitor",
			"Taster",
			"Truffle Maker",
			"Supply Worker",
			"Packager",
			"Inspector",
			"Machine Operator",
			"Janitor",
		],
	},
	Subway: {
		name: "Subway",
		version: 2,
		roles: [
			"Tourist",
			"Subway Operator",
			"Ticket Inspector",
			"Pregnant Lady",
			"Pickpocket",
			"Cleaner",
			"Businessman",
			"Ticket Seller",
			"Old Lady",
			"Blind Man",
		],
	},
	"Coal Mine": {
		name: "Coal Mine",
		version: 2,
		roles: [
			"Safety Inspector",
			"Miner",
			"Overseer",
			"Dump Truck Operator",
			"Driller",
			"Coordinator",
			"Blasting Engineer",
			"Solid Waste Engineer",
			"Worker",
		],
	},
	"Rock Concert": {
		name: "Rock Concert",
		version: 2,
		roles: [
			"Dancer",
			"Singer",
			"Fan",
			"Guitarist",
			"Drummer",
			"Roadie",
			"Stage Diver",
			"Security Guard",
			"Bassist",
			"Sound Technician",
		],
	},
	"Jazz Club": {
		name: "Jazz Club",
		version: 2,
		roles: [
			"Bouncer",
			"Drummer",
			"Pianist",
			"Saxophonist",
			"Singer",
			"Jazz Fanatic",
			"Dancer",
			"Barman",
			"VIP",
			"Waiter",
		],
	},
	Wedding: {
		name: "Wedding",
		version: 2,
		roles: [
			"Ring Bearer",
			"Groom",
			"Bride",
			"Officiant",
			"Photographer",
			"Flower Girl",
			"Father of the Bride",
			"Wedding Crasher",
			"Best Man",
			"Maid of Honor",
			"Relative",
		],
	},
	"Gas Station": {
		name: "Gas Station",
		version: 2,
		roles: [
			"Car Enthusiast",
			"Service Attendant",
			"Shopkeeper",
			"Customer",
			"Car Washer",
			"Cashier",
			"Climate Change Activist",
			"Manager",
		],
	},
	"Harbor Docks": {
		name: "Harbor Docks",
		version: 2,
		roles: [
			"Loader",
			"Salty Old Pirate",
			"Captain",
			"Sailor",
			"Fisherman",
			"Exporter",
			"Cargo Overseer",
			"Cargo Inspector",
			"Smuggler",
		],
	},
	"Sightseeing Bus": {
		name: "Sightseeing Bus",
		version: 2,
		roles: [
			"Old Man",
			"Lone Tourist",
			"Driver",
			"Annoying Child",
			"Tourist",
			"Tour Guide",
			"Photographer",
			"Lost Person",
		],
	},
};
